//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/protobuf/descriptor.proto

package com.google.protobuf;

@kotlin.jvm.JvmSynthetic
public inline fun descriptorProto(block: com.google.protobuf.DescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.DescriptorProto =
  com.google.protobuf.DescriptorProtoKt.Dsl._create(com.google.protobuf.DescriptorProtos.DescriptorProto.newBuilder()).apply { block() }._build()
public object DescriptorProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.DescriptorProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.DescriptorProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.DescriptorProto = _builder.build()

    /**
     * <code>optional string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>optional string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FieldProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.FieldDescriptorProto field = 2;</code>
     */
     public val field: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, FieldProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFieldList()
      )
    /**
     * <code>repeated .google.protobuf.FieldDescriptorProto field = 2;</code>
     * @param value The field to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addField")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, FieldProxy>.add(value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      _builder.addField(value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto field = 2;</code>
     * @param value The field to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignField")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, FieldProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto field = 2;</code>
     * @param values The field to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllField")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, FieldProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FieldDescriptorProto>) {
      _builder.addAllField(values)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto field = 2;</code>
     * @param values The field to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllField")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, FieldProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FieldDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto field = 2;</code>
     * @param index The index to set the value at.
     * @param value The field to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setField")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, FieldProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      _builder.setField(index, value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto field = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearField")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, FieldProxy>.clear() {
      _builder.clearField()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtensionProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 6;</code>
     */
     public val extension: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getExtensionList()
      )
    /**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 6;</code>
     * @param value The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.add(value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      _builder.addExtension(value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 6;</code>
     * @param value The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignExtension")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 6;</code>
     * @param values The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FieldDescriptorProto>) {
      _builder.addAllExtension(values)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 6;</code>
     * @param values The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllExtension")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FieldDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 6;</code>
     * @param index The index to set the value at.
     * @param value The extension to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setExtension")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      _builder.setExtension(index, value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.clear() {
      _builder.clearExtension()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NestedTypeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.DescriptorProto nested_type = 3;</code>
     */
     public val nestedType: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, NestedTypeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getNestedTypeList()
      )
    /**
     * <code>repeated .google.protobuf.DescriptorProto nested_type = 3;</code>
     * @param value The nestedType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addNestedType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, NestedTypeProxy>.add(value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      _builder.addNestedType(value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto nested_type = 3;</code>
     * @param value The nestedType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignNestedType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, NestedTypeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto nested_type = 3;</code>
     * @param values The nestedType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllNestedType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, NestedTypeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto>) {
      _builder.addAllNestedType(values)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto nested_type = 3;</code>
     * @param values The nestedType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllNestedType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, NestedTypeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto nested_type = 3;</code>
     * @param index The index to set the value at.
     * @param value The nestedType to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setNestedType")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, NestedTypeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      _builder.setNestedType(index, value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto nested_type = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearNestedType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, NestedTypeProxy>.clear() {
      _builder.clearNestedType()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EnumTypeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4;</code>
     */
     public val enumType: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEnumTypeList()
      )
    /**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4;</code>
     * @param value The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.add(value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      _builder.addEnumType(value)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4;</code>
     * @param value The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEnumType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4;</code>
     * @param values The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumDescriptorProto>) {
      _builder.addAllEnumType(values)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4;</code>
     * @param values The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEnumType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4;</code>
     * @param index The index to set the value at.
     * @param value The enumType to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEnumType")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      _builder.setEnumType(index, value)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.clear() {
      _builder.clearEnumType()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtensionRangeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;</code>
     */
     public val extensionRange: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange, ExtensionRangeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getExtensionRangeList()
      )
    /**
     * <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;</code>
     * @param value The extensionRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addExtensionRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange, ExtensionRangeProxy>.add(value: com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange) {
      _builder.addExtensionRange(value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;</code>
     * @param value The extensionRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignExtensionRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange, ExtensionRangeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;</code>
     * @param values The extensionRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllExtensionRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange, ExtensionRangeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange>) {
      _builder.addAllExtensionRange(values)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;</code>
     * @param values The extensionRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllExtensionRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange, ExtensionRangeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;</code>
     * @param index The index to set the value at.
     * @param value The extensionRange to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setExtensionRange")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange, ExtensionRangeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange) {
      _builder.setExtensionRange(index, value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearExtensionRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange, ExtensionRangeProxy>.clear() {
      _builder.clearExtensionRange()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OneofDeclProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8;</code>
     */
     public val oneofDecl: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.OneofDescriptorProto, OneofDeclProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOneofDeclList()
      )
    /**
     * <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8;</code>
     * @param value The oneofDecl to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOneofDecl")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.OneofDescriptorProto, OneofDeclProxy>.add(value: com.google.protobuf.DescriptorProtos.OneofDescriptorProto) {
      _builder.addOneofDecl(value)
    }/**
     * <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8;</code>
     * @param value The oneofDecl to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOneofDecl")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.OneofDescriptorProto, OneofDeclProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.OneofDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8;</code>
     * @param values The oneofDecl to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOneofDecl")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.OneofDescriptorProto, OneofDeclProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.OneofDescriptorProto>) {
      _builder.addAllOneofDecl(values)
    }/**
     * <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8;</code>
     * @param values The oneofDecl to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOneofDecl")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.OneofDescriptorProto, OneofDeclProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.OneofDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8;</code>
     * @param index The index to set the value at.
     * @param value The oneofDecl to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOneofDecl")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.OneofDescriptorProto, OneofDeclProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.OneofDescriptorProto) {
      _builder.setOneofDecl(index, value)
    }/**
     * <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOneofDecl")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.OneofDescriptorProto, OneofDeclProxy>.clear() {
      _builder.clearOneofDecl()
    }
    /**
     * <code>optional .google.protobuf.MessageOptions options = 7;</code>
     */
    public var options: com.google.protobuf.DescriptorProtos.MessageOptions
      @JvmName("getOptions")
      get() = _builder.getOptions()
      @JvmName("setOptions")
      set(value) {
        _builder.setOptions(value)
      }
    /**
     * <code>optional .google.protobuf.MessageOptions options = 7;</code>
     */
    public fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * <code>optional .google.protobuf.MessageOptions options = 7;</code>
     * @return Whether the options field is set.
     */
    public fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReservedRangeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9;</code>
     */
     public val reservedRange: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange, ReservedRangeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getReservedRangeList()
      )
    /**
     * <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9;</code>
     * @param value The reservedRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addReservedRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange, ReservedRangeProxy>.add(value: com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange) {
      _builder.addReservedRange(value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9;</code>
     * @param value The reservedRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignReservedRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange, ReservedRangeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9;</code>
     * @param values The reservedRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllReservedRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange, ReservedRangeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange>) {
      _builder.addAllReservedRange(values)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9;</code>
     * @param values The reservedRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllReservedRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange, ReservedRangeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9;</code>
     * @param index The index to set the value at.
     * @param value The reservedRange to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setReservedRange")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange, ReservedRangeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange) {
      _builder.setReservedRange(index, value)
    }/**
     * <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearReservedRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange, ReservedRangeProxy>.clear() {
      _builder.clearReservedRange()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReservedNameProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 10;</code>
     * @return A list containing the reservedName.
     */
    public val reservedName: com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getReservedNameList()
      )
    /**
     * <pre>
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 10;</code>
     * @param value The reservedName to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addReservedName")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.add(value: kotlin.String) {
      _builder.addReservedName(value)
    }
    /**
     * <pre>
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 10;</code>
     * @param value The reservedName to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignReservedName")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 10;</code>
     * @param values The reservedName to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllReservedName")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllReservedName(values)
    }
    /**
     * <pre>
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 10;</code>
     * @param values The reservedName to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllReservedName")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 10;</code>
     * @param index The index to set the value at.
     * @param value The reservedName to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setReservedName")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setReservedName(index, value)
    }/**
     * <pre>
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearReservedName")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.clear() {
      _builder.clearReservedName()
    }}
  @kotlin.jvm.JvmSynthetic
  public inline fun extensionRange(block: com.google.protobuf.DescriptorProtoKt.ExtensionRangeKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange =
    com.google.protobuf.DescriptorProtoKt.ExtensionRangeKt.Dsl._create(com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange.newBuilder()).apply { block() }._build()
  public object ExtensionRangeKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange = _builder.build()

      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       */
      public var start: kotlin.Int
        @JvmName("getStart")
        get() = _builder.getStart()
        @JvmName("setStart")
        set(value) {
          _builder.setStart(value)
        }
      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       */
      public fun clearStart() {
        _builder.clearStart()
      }
      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       * @return Whether the start field is set.
       */
      public fun hasStart(): kotlin.Boolean {
        return _builder.hasStart()
      }

      /**
       * <pre>
       * Exclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       */
      public var end: kotlin.Int
        @JvmName("getEnd")
        get() = _builder.getEnd()
        @JvmName("setEnd")
        set(value) {
          _builder.setEnd(value)
        }
      /**
       * <pre>
       * Exclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       */
      public fun clearEnd() {
        _builder.clearEnd()
      }
      /**
       * <pre>
       * Exclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       * @return Whether the end field is set.
       */
      public fun hasEnd(): kotlin.Boolean {
        return _builder.hasEnd()
      }

      /**
       * <code>optional .google.protobuf.ExtensionRangeOptions options = 3;</code>
       */
      public var options: com.google.protobuf.DescriptorProtos.ExtensionRangeOptions
        @JvmName("getOptions")
        get() = _builder.getOptions()
        @JvmName("setOptions")
        set(value) {
          _builder.setOptions(value)
        }
      /**
       * <code>optional .google.protobuf.ExtensionRangeOptions options = 3;</code>
       */
      public fun clearOptions() {
        _builder.clearOptions()
      }
      /**
       * <code>optional .google.protobuf.ExtensionRangeOptions options = 3;</code>
       * @return Whether the options field is set.
       */
      public fun hasOptions(): kotlin.Boolean {
        return _builder.hasOptions()
      }
    }
  }
  @kotlin.jvm.JvmSynthetic
  public inline fun reservedRange(block: com.google.protobuf.DescriptorProtoKt.ReservedRangeKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange =
    com.google.protobuf.DescriptorProtoKt.ReservedRangeKt.Dsl._create(com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange.newBuilder()).apply { block() }._build()
  public object ReservedRangeKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange = _builder.build()

      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       */
      public var start: kotlin.Int
        @JvmName("getStart")
        get() = _builder.getStart()
        @JvmName("setStart")
        set(value) {
          _builder.setStart(value)
        }
      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       */
      public fun clearStart() {
        _builder.clearStart()
      }
      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       * @return Whether the start field is set.
       */
      public fun hasStart(): kotlin.Boolean {
        return _builder.hasStart()
      }

      /**
       * <pre>
       * Exclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       */
      public var end: kotlin.Int
        @JvmName("getEnd")
        get() = _builder.getEnd()
        @JvmName("setEnd")
        set(value) {
          _builder.setEnd(value)
        }
      /**
       * <pre>
       * Exclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       */
      public fun clearEnd() {
        _builder.clearEnd()
      }
      /**
       * <pre>
       * Exclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       * @return Whether the end field is set.
       */
      public fun hasEnd(): kotlin.Boolean {
        return _builder.hasEnd()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.DescriptorProto.copy(block: com.google.protobuf.DescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.DescriptorProto =
  com.google.protobuf.DescriptorProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange.copy(block: com.google.protobuf.DescriptorProtoKt.ExtensionRangeKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.DescriptorProto.ExtensionRange =
  com.google.protobuf.DescriptorProtoKt.ExtensionRangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange.copy(block: com.google.protobuf.DescriptorProtoKt.ReservedRangeKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.DescriptorProto.ReservedRange =
  com.google.protobuf.DescriptorProtoKt.ReservedRangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()
