//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/protobuf/descriptor.proto

package com.google.protobuf;

@kotlin.jvm.JvmSynthetic
public inline fun enumDescriptorProto(block: com.google.protobuf.EnumDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.EnumDescriptorProto =
  com.google.protobuf.EnumDescriptorProtoKt.Dsl._create(com.google.protobuf.DescriptorProtos.EnumDescriptorProto.newBuilder()).apply { block() }._build()
public object EnumDescriptorProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.EnumDescriptorProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.EnumDescriptorProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.EnumDescriptorProto = _builder.build()

    /**
     * <code>optional string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>optional string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ValueProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.EnumValueDescriptorProto value = 2;</code>
     */
     public val value: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto, ValueProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getValueList()
      )
    /**
     * <code>repeated .google.protobuf.EnumValueDescriptorProto value = 2;</code>
     * @param value The value to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addValue")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto, ValueProxy>.add(value: com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto) {
      _builder.addValue(value)
    }/**
     * <code>repeated .google.protobuf.EnumValueDescriptorProto value = 2;</code>
     * @param value The value to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignValue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto, ValueProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.EnumValueDescriptorProto value = 2;</code>
     * @param values The value to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllValue")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto, ValueProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto>) {
      _builder.addAllValue(values)
    }/**
     * <code>repeated .google.protobuf.EnumValueDescriptorProto value = 2;</code>
     * @param values The value to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllValue")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto, ValueProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.EnumValueDescriptorProto value = 2;</code>
     * @param index The index to set the value at.
     * @param value The value to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setValue")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto, ValueProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto) {
      _builder.setValue(index, value)
    }/**
     * <code>repeated .google.protobuf.EnumValueDescriptorProto value = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearValue")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumValueDescriptorProto, ValueProxy>.clear() {
      _builder.clearValue()
    }
    /**
     * <code>optional .google.protobuf.EnumOptions options = 3;</code>
     */
    public var options: com.google.protobuf.DescriptorProtos.EnumOptions
      @JvmName("getOptions")
      get() = _builder.getOptions()
      @JvmName("setOptions")
      set(value) {
        _builder.setOptions(value)
      }
    /**
     * <code>optional .google.protobuf.EnumOptions options = 3;</code>
     */
    public fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * <code>optional .google.protobuf.EnumOptions options = 3;</code>
     * @return Whether the options field is set.
     */
    public fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReservedRangeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Range of reserved numeric values. Reserved numeric values may not be used
     * by enum values in the same enum declaration. Reserved ranges may not
     * overlap.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4;</code>
     */
     public val reservedRange: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange, ReservedRangeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getReservedRangeList()
      )
    /**
     * <pre>
     * Range of reserved numeric values. Reserved numeric values may not be used
     * by enum values in the same enum declaration. Reserved ranges may not
     * overlap.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4;</code>
     * @param value The reservedRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addReservedRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange, ReservedRangeProxy>.add(value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange) {
      _builder.addReservedRange(value)
    }/**
     * <pre>
     * Range of reserved numeric values. Reserved numeric values may not be used
     * by enum values in the same enum declaration. Reserved ranges may not
     * overlap.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4;</code>
     * @param value The reservedRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignReservedRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange, ReservedRangeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange) {
      add(value)
    }/**
     * <pre>
     * Range of reserved numeric values. Reserved numeric values may not be used
     * by enum values in the same enum declaration. Reserved ranges may not
     * overlap.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4;</code>
     * @param values The reservedRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllReservedRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange, ReservedRangeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange>) {
      _builder.addAllReservedRange(values)
    }/**
     * <pre>
     * Range of reserved numeric values. Reserved numeric values may not be used
     * by enum values in the same enum declaration. Reserved ranges may not
     * overlap.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4;</code>
     * @param values The reservedRange to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllReservedRange")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange, ReservedRangeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange>) {
      addAll(values)
    }/**
     * <pre>
     * Range of reserved numeric values. Reserved numeric values may not be used
     * by enum values in the same enum declaration. Reserved ranges may not
     * overlap.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4;</code>
     * @param index The index to set the value at.
     * @param value The reservedRange to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setReservedRange")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange, ReservedRangeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange) {
      _builder.setReservedRange(index, value)
    }/**
     * <pre>
     * Range of reserved numeric values. Reserved numeric values may not be used
     * by enum values in the same enum declaration. Reserved ranges may not
     * overlap.
     * </pre>
     *
     * <code>repeated .google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearReservedRange")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange, ReservedRangeProxy>.clear() {
      _builder.clearReservedRange()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReservedNameProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Reserved enum value names, which may not be reused. A given name may only
     * be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 5;</code>
     * @return A list containing the reservedName.
     */
    public val reservedName: com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getReservedNameList()
      )
    /**
     * <pre>
     * Reserved enum value names, which may not be reused. A given name may only
     * be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 5;</code>
     * @param value The reservedName to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addReservedName")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.add(value: kotlin.String) {
      _builder.addReservedName(value)
    }
    /**
     * <pre>
     * Reserved enum value names, which may not be reused. A given name may only
     * be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 5;</code>
     * @param value The reservedName to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignReservedName")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * Reserved enum value names, which may not be reused. A given name may only
     * be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 5;</code>
     * @param values The reservedName to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllReservedName")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllReservedName(values)
    }
    /**
     * <pre>
     * Reserved enum value names, which may not be reused. A given name may only
     * be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 5;</code>
     * @param values The reservedName to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllReservedName")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * Reserved enum value names, which may not be reused. A given name may only
     * be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 5;</code>
     * @param index The index to set the value at.
     * @param value The reservedName to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setReservedName")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setReservedName(index, value)
    }/**
     * <pre>
     * Reserved enum value names, which may not be reused. A given name may only
     * be reserved once.
     * </pre>
     *
     * <code>repeated string reserved_name = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearReservedName")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ReservedNameProxy>.clear() {
      _builder.clearReservedName()
    }}
  @kotlin.jvm.JvmSynthetic
  public inline fun enumReservedRange(block: com.google.protobuf.EnumDescriptorProtoKt.EnumReservedRangeKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange =
    com.google.protobuf.EnumDescriptorProtoKt.EnumReservedRangeKt.Dsl._create(com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange.newBuilder()).apply { block() }._build()
  public object EnumReservedRangeKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange = _builder.build()

      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       */
      public var start: kotlin.Int
        @JvmName("getStart")
        get() = _builder.getStart()
        @JvmName("setStart")
        set(value) {
          _builder.setStart(value)
        }
      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       */
      public fun clearStart() {
        _builder.clearStart()
      }
      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 start = 1;</code>
       * @return Whether the start field is set.
       */
      public fun hasStart(): kotlin.Boolean {
        return _builder.hasStart()
      }

      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       */
      public var end: kotlin.Int
        @JvmName("getEnd")
        get() = _builder.getEnd()
        @JvmName("setEnd")
        set(value) {
          _builder.setEnd(value)
        }
      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       */
      public fun clearEnd() {
        _builder.clearEnd()
      }
      /**
       * <pre>
       * Inclusive.
       * </pre>
       *
       * <code>optional int32 end = 2;</code>
       * @return Whether the end field is set.
       */
      public fun hasEnd(): kotlin.Boolean {
        return _builder.hasEnd()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.EnumDescriptorProto.copy(block: com.google.protobuf.EnumDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.EnumDescriptorProto =
  com.google.protobuf.EnumDescriptorProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange.copy(block: com.google.protobuf.EnumDescriptorProtoKt.EnumReservedRangeKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.EnumDescriptorProto.EnumReservedRange =
  com.google.protobuf.EnumDescriptorProtoKt.EnumReservedRangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()
