//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/protobuf/descriptor.proto

package com.google.protobuf;

@kotlin.jvm.JvmSynthetic
public inline fun generatedCodeInfo(block: com.google.protobuf.GeneratedCodeInfoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo =
  com.google.protobuf.GeneratedCodeInfoKt.Dsl._create(com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.newBuilder()).apply { block() }._build()
public object GeneratedCodeInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AnnotationProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     * </pre>
     *
     * <code>repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1;</code>
     */
     public val annotation: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getAnnotationList()
      )
    /**
     * <pre>
     * An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     * </pre>
     *
     * <code>repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1;</code>
     * @param value The annotation to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAnnotation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.add(value: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation) {
      _builder.addAnnotation(value)
    }/**
     * <pre>
     * An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     * </pre>
     *
     * <code>repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1;</code>
     * @param value The annotation to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAnnotation")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation) {
      add(value)
    }/**
     * <pre>
     * An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     * </pre>
     *
     * <code>repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1;</code>
     * @param values The annotation to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllAnnotation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation>) {
      _builder.addAllAnnotation(values)
    }/**
     * <pre>
     * An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     * </pre>
     *
     * <code>repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1;</code>
     * @param values The annotation to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllAnnotation")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation>) {
      addAll(values)
    }/**
     * <pre>
     * An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     * </pre>
     *
     * <code>repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1;</code>
     * @param index The index to set the value at.
     * @param value The annotation to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setAnnotation")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation) {
      _builder.setAnnotation(index, value)
    }/**
     * <pre>
     * An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     * </pre>
     *
     * <code>repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearAnnotation")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation, AnnotationProxy>.clear() {
      _builder.clearAnnotation()
    }}
  @kotlin.jvm.JvmSynthetic
  public inline fun annotation(block: com.google.protobuf.GeneratedCodeInfoKt.AnnotationKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation =
    com.google.protobuf.GeneratedCodeInfoKt.AnnotationKt.Dsl._create(com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.newBuilder()).apply { block() }._build()
  public object AnnotationKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class PathProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * <pre>
       * Identifies the element in the original source .proto file. This field
       * is formatted the same as SourceCodeInfo.Location.path.
       * </pre>
       *
       * <code>repeated int32 path = 1 [packed = true];</code>
       */
       public val path: com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.getPathList()
        )
      /**
       * <pre>
       * Identifies the element in the original source .proto file. This field
       * is formatted the same as SourceCodeInfo.Location.path.
       * </pre>
       *
       * <code>repeated int32 path = 1 [packed = true];</code>
       * @param value The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.add(value: kotlin.Int) {
        _builder.addPath(value)
      }/**
       * <pre>
       * Identifies the element in the original source .proto file. This field
       * is formatted the same as SourceCodeInfo.Location.path.
       * </pre>
       *
       * <code>repeated int32 path = 1 [packed = true];</code>
       * @param value The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignPath")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.plusAssign(value: kotlin.Int) {
        add(value)
      }/**
       * <pre>
       * Identifies the element in the original source .proto file. This field
       * is formatted the same as SourceCodeInfo.Location.path.
       * </pre>
       *
       * <code>repeated int32 path = 1 [packed = true];</code>
       * @param values The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
        _builder.addAllPath(values)
      }/**
       * <pre>
       * Identifies the element in the original source .proto file. This field
       * is formatted the same as SourceCodeInfo.Location.path.
       * </pre>
       *
       * <code>repeated int32 path = 1 [packed = true];</code>
       * @param values The path to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllPath")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
        addAll(values)
      }/**
       * <pre>
       * Identifies the element in the original source .proto file. This field
       * is formatted the same as SourceCodeInfo.Location.path.
       * </pre>
       *
       * <code>repeated int32 path = 1 [packed = true];</code>
       * @param index The index to set the value at.
       * @param value The path to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setPath")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.set(index: kotlin.Int, value: kotlin.Int) {
        _builder.setPath(index, value)
      }/**
       * <pre>
       * Identifies the element in the original source .proto file. This field
       * is formatted the same as SourceCodeInfo.Location.path.
       * </pre>
       *
       * <code>repeated int32 path = 1 [packed = true];</code>
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearPath")
      public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PathProxy>.clear() {
        _builder.clearPath()
      }
      /**
       * <pre>
       * Identifies the filesystem path to the original source .proto.
       * </pre>
       *
       * <code>optional string source_file = 2;</code>
       */
      public var sourceFile: kotlin.String
        @JvmName("getSourceFile")
        get() = _builder.getSourceFile()
        @JvmName("setSourceFile")
        set(value) {
          _builder.setSourceFile(value)
        }
      /**
       * <pre>
       * Identifies the filesystem path to the original source .proto.
       * </pre>
       *
       * <code>optional string source_file = 2;</code>
       */
      public fun clearSourceFile() {
        _builder.clearSourceFile()
      }
      /**
       * <pre>
       * Identifies the filesystem path to the original source .proto.
       * </pre>
       *
       * <code>optional string source_file = 2;</code>
       * @return Whether the sourceFile field is set.
       */
      public fun hasSourceFile(): kotlin.Boolean {
        return _builder.hasSourceFile()
      }

      /**
       * <pre>
       * Identifies the starting offset in bytes in the generated code
       * that relates to the identified object.
       * </pre>
       *
       * <code>optional int32 begin = 3;</code>
       */
      public var begin: kotlin.Int
        @JvmName("getBegin")
        get() = _builder.getBegin()
        @JvmName("setBegin")
        set(value) {
          _builder.setBegin(value)
        }
      /**
       * <pre>
       * Identifies the starting offset in bytes in the generated code
       * that relates to the identified object.
       * </pre>
       *
       * <code>optional int32 begin = 3;</code>
       */
      public fun clearBegin() {
        _builder.clearBegin()
      }
      /**
       * <pre>
       * Identifies the starting offset in bytes in the generated code
       * that relates to the identified object.
       * </pre>
       *
       * <code>optional int32 begin = 3;</code>
       * @return Whether the begin field is set.
       */
      public fun hasBegin(): kotlin.Boolean {
        return _builder.hasBegin()
      }

      /**
       * <pre>
       * Identifies the ending offset in bytes in the generated code that
       * relates to the identified offset. The end offset should be one past
       * the last relevant byte (so the length of the text = end - begin).
       * </pre>
       *
       * <code>optional int32 end = 4;</code>
       */
      public var end: kotlin.Int
        @JvmName("getEnd")
        get() = _builder.getEnd()
        @JvmName("setEnd")
        set(value) {
          _builder.setEnd(value)
        }
      /**
       * <pre>
       * Identifies the ending offset in bytes in the generated code that
       * relates to the identified offset. The end offset should be one past
       * the last relevant byte (so the length of the text = end - begin).
       * </pre>
       *
       * <code>optional int32 end = 4;</code>
       */
      public fun clearEnd() {
        _builder.clearEnd()
      }
      /**
       * <pre>
       * Identifies the ending offset in bytes in the generated code that
       * relates to the identified offset. The end offset should be one past
       * the last relevant byte (so the length of the text = end - begin).
       * </pre>
       *
       * <code>optional int32 end = 4;</code>
       * @return Whether the end field is set.
       */
      public fun hasEnd(): kotlin.Boolean {
        return _builder.hasEnd()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.copy(block: com.google.protobuf.GeneratedCodeInfoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo =
  com.google.protobuf.GeneratedCodeInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation.copy(block: com.google.protobuf.GeneratedCodeInfoKt.AnnotationKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.GeneratedCodeInfo.Annotation =
  com.google.protobuf.GeneratedCodeInfoKt.AnnotationKt.Dsl._create(this.toBuilder()).apply { block() }._build()
