//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/protobuf/descriptor.proto

package com.google.protobuf;

@kotlin.jvm.JvmSynthetic
public inline fun uninterpretedOption(block: com.google.protobuf.UninterpretedOptionKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.UninterpretedOption =
  com.google.protobuf.UninterpretedOptionKt.Dsl._create(com.google.protobuf.DescriptorProtos.UninterpretedOption.newBuilder()).apply { block() }._build()
public object UninterpretedOptionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.UninterpretedOption.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.UninterpretedOption.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.UninterpretedOption = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class NameProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
     public val name: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart, NameProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getNameList()
      )
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     * @param value The name to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addName")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart, NameProxy>.add(value: com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart) {
      _builder.addName(value)
    }/**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     * @param value The name to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignName")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart, NameProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     * @param values The name to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllName")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart, NameProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart>) {
      _builder.addAllName(values)
    }/**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     * @param values The name to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllName")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart, NameProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     * @param index The index to set the value at.
     * @param value The name to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setName")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart, NameProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart) {
      _builder.setName(index, value)
    }/**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearName")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart, NameProxy>.clear() {
      _builder.clearName()
    }
    /**
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     *
     * <code>optional string identifier_value = 3;</code>
     */
    public var identifierValue: kotlin.String
      @JvmName("getIdentifierValue")
      get() = _builder.getIdentifierValue()
      @JvmName("setIdentifierValue")
      set(value) {
        _builder.setIdentifierValue(value)
      }
    /**
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     *
     * <code>optional string identifier_value = 3;</code>
     */
    public fun clearIdentifierValue() {
      _builder.clearIdentifierValue()
    }
    /**
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     *
     * <code>optional string identifier_value = 3;</code>
     * @return Whether the identifierValue field is set.
     */
    public fun hasIdentifierValue(): kotlin.Boolean {
      return _builder.hasIdentifierValue()
    }

    /**
     * <code>optional uint64 positive_int_value = 4;</code>
     */
    public var positiveIntValue: kotlin.Long
      @JvmName("getPositiveIntValue")
      get() = _builder.getPositiveIntValue()
      @JvmName("setPositiveIntValue")
      set(value) {
        _builder.setPositiveIntValue(value)
      }
    /**
     * <code>optional uint64 positive_int_value = 4;</code>
     */
    public fun clearPositiveIntValue() {
      _builder.clearPositiveIntValue()
    }
    /**
     * <code>optional uint64 positive_int_value = 4;</code>
     * @return Whether the positiveIntValue field is set.
     */
    public fun hasPositiveIntValue(): kotlin.Boolean {
      return _builder.hasPositiveIntValue()
    }

    /**
     * <code>optional int64 negative_int_value = 5;</code>
     */
    public var negativeIntValue: kotlin.Long
      @JvmName("getNegativeIntValue")
      get() = _builder.getNegativeIntValue()
      @JvmName("setNegativeIntValue")
      set(value) {
        _builder.setNegativeIntValue(value)
      }
    /**
     * <code>optional int64 negative_int_value = 5;</code>
     */
    public fun clearNegativeIntValue() {
      _builder.clearNegativeIntValue()
    }
    /**
     * <code>optional int64 negative_int_value = 5;</code>
     * @return Whether the negativeIntValue field is set.
     */
    public fun hasNegativeIntValue(): kotlin.Boolean {
      return _builder.hasNegativeIntValue()
    }

    /**
     * <code>optional double double_value = 6;</code>
     */
    public var doubleValue: kotlin.Double
      @JvmName("getDoubleValue")
      get() = _builder.getDoubleValue()
      @JvmName("setDoubleValue")
      set(value) {
        _builder.setDoubleValue(value)
      }
    /**
     * <code>optional double double_value = 6;</code>
     */
    public fun clearDoubleValue() {
      _builder.clearDoubleValue()
    }
    /**
     * <code>optional double double_value = 6;</code>
     * @return Whether the doubleValue field is set.
     */
    public fun hasDoubleValue(): kotlin.Boolean {
      return _builder.hasDoubleValue()
    }

    /**
     * <code>optional bytes string_value = 7;</code>
     */
    public var stringValue: com.google.protobuf.ByteString
      @JvmName("getStringValue")
      get() = _builder.getStringValue()
      @JvmName("setStringValue")
      set(value) {
        _builder.setStringValue(value)
      }
    /**
     * <code>optional bytes string_value = 7;</code>
     */
    public fun clearStringValue() {
      _builder.clearStringValue()
    }
    /**
     * <code>optional bytes string_value = 7;</code>
     * @return Whether the stringValue field is set.
     */
    public fun hasStringValue(): kotlin.Boolean {
      return _builder.hasStringValue()
    }

    /**
     * <code>optional string aggregate_value = 8;</code>
     */
    public var aggregateValue: kotlin.String
      @JvmName("getAggregateValue")
      get() = _builder.getAggregateValue()
      @JvmName("setAggregateValue")
      set(value) {
        _builder.setAggregateValue(value)
      }
    /**
     * <code>optional string aggregate_value = 8;</code>
     */
    public fun clearAggregateValue() {
      _builder.clearAggregateValue()
    }
    /**
     * <code>optional string aggregate_value = 8;</code>
     * @return Whether the aggregateValue field is set.
     */
    public fun hasAggregateValue(): kotlin.Boolean {
      return _builder.hasAggregateValue()
    }
  }
  @kotlin.jvm.JvmSynthetic
  public inline fun namePart(block: com.google.protobuf.UninterpretedOptionKt.NamePartKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart =
    com.google.protobuf.UninterpretedOptionKt.NamePartKt.Dsl._create(com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart.newBuilder()).apply { block() }._build()
  public object NamePartKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart = _builder.build()

      /**
       * <code>required string name_part = 1;</code>
       */
      public var namePart: kotlin.String
        @JvmName("getNamePart")
        get() = _builder.getNamePart()
        @JvmName("setNamePart")
        set(value) {
          _builder.setNamePart(value)
        }
      /**
       * <code>required string name_part = 1;</code>
       */
      public fun clearNamePart() {
        _builder.clearNamePart()
      }
      /**
       * <code>required string name_part = 1;</code>
       * @return Whether the namePart field is set.
       */
      public fun hasNamePart(): kotlin.Boolean {
        return _builder.hasNamePart()
      }

      /**
       * <code>required bool is_extension = 2;</code>
       */
      public var isExtension: kotlin.Boolean
        @JvmName("getIsExtension")
        get() = _builder.getIsExtension()
        @JvmName("setIsExtension")
        set(value) {
          _builder.setIsExtension(value)
        }
      /**
       * <code>required bool is_extension = 2;</code>
       */
      public fun clearIsExtension() {
        _builder.clearIsExtension()
      }
      /**
       * <code>required bool is_extension = 2;</code>
       * @return Whether the isExtension field is set.
       */
      public fun hasIsExtension(): kotlin.Boolean {
        return _builder.hasIsExtension()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.UninterpretedOption.copy(block: com.google.protobuf.UninterpretedOptionKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.UninterpretedOption =
  com.google.protobuf.UninterpretedOptionKt.Dsl._create(this.toBuilder()).apply { block() }._build()
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart.copy(block: com.google.protobuf.UninterpretedOptionKt.NamePartKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.UninterpretedOption.NamePart =
  com.google.protobuf.UninterpretedOptionKt.NamePartKt.Dsl._create(this.toBuilder()).apply { block() }._build()
