//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/protobuf/descriptor.proto

package com.google.protobuf;

@kotlin.jvm.JvmSynthetic
public inline fun fileDescriptorSet(block: com.google.protobuf.FileDescriptorSetKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FileDescriptorSet =
  com.google.protobuf.FileDescriptorSetKt.Dsl._create(com.google.protobuf.DescriptorProtos.FileDescriptorSet.newBuilder()).apply { block() }._build()
public object FileDescriptorSetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.FileDescriptorSet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.FileDescriptorSet = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FileProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.FileDescriptorProto file = 1;</code>
     */
     public val file: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FileDescriptorProto, FileProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getFileList()
      )
    /**
     * <code>repeated .google.protobuf.FileDescriptorProto file = 1;</code>
     * @param value The file to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFile")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FileDescriptorProto, FileProxy>.add(value: com.google.protobuf.DescriptorProtos.FileDescriptorProto) {
      _builder.addFile(value)
    }/**
     * <code>repeated .google.protobuf.FileDescriptorProto file = 1;</code>
     * @param value The file to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFile")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FileDescriptorProto, FileProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.FileDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.FileDescriptorProto file = 1;</code>
     * @param values The file to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFile")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FileDescriptorProto, FileProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FileDescriptorProto>) {
      _builder.addAllFile(values)
    }/**
     * <code>repeated .google.protobuf.FileDescriptorProto file = 1;</code>
     * @param values The file to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFile")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FileDescriptorProto, FileProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FileDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.FileDescriptorProto file = 1;</code>
     * @param index The index to set the value at.
     * @param value The file to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFile")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FileDescriptorProto, FileProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.FileDescriptorProto) {
      _builder.setFile(index, value)
    }/**
     * <code>repeated .google.protobuf.FileDescriptorProto file = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFile")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FileDescriptorProto, FileProxy>.clear() {
      _builder.clearFile()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.FileDescriptorSet.copy(block: com.google.protobuf.FileDescriptorSetKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FileDescriptorSet =
  com.google.protobuf.FileDescriptorSetKt.Dsl._create(this.toBuilder()).apply { block() }._build()
