//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: google/protobuf/descriptor.proto

package com.google.protobuf;

@kotlin.jvm.JvmSynthetic
public inline fun fileDescriptorProto(block: com.google.protobuf.FileDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FileDescriptorProto =
  com.google.protobuf.FileDescriptorProtoKt.Dsl._create(com.google.protobuf.DescriptorProtos.FileDescriptorProto.newBuilder()).apply { block() }._build()
public object FileDescriptorProtoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.google.protobuf.DescriptorProtos.FileDescriptorProto = _builder.build()

    /**
     * <pre>
     * file name, relative to root of source tree
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <pre>
     * file name, relative to root of source tree
     * </pre>
     *
     * <code>optional string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * <pre>
     * file name, relative to root of source tree
     * </pre>
     *
     * <code>optional string name = 1;</code>
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * <pre>
     * e.g. "foo", "foo.bar", etc.
     * </pre>
     *
     * <code>optional string package = 2;</code>
     */
    public var package_: kotlin.String
      @JvmName("getPackage_")
      get() = _builder.getPackage()
      @JvmName("setPackage_")
      set(value) {
        _builder.setPackage(value)
      }
    /**
     * <pre>
     * e.g. "foo", "foo.bar", etc.
     * </pre>
     *
     * <code>optional string package = 2;</code>
     */
    public fun clearPackage_() {
      _builder.clearPackage()
    }
    /**
     * <pre>
     * e.g. "foo", "foo.bar", etc.
     * </pre>
     *
     * <code>optional string package = 2;</code>
     * @return Whether the package field is set.
     */
    public fun hasPackage_(): kotlin.Boolean {
      return _builder.hasPackage()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DependencyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Names of files imported by this file.
     * </pre>
     *
     * <code>repeated string dependency = 3;</code>
     * @return A list containing the dependency.
     */
    public val dependency: com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getDependencyList()
      )
    /**
     * <pre>
     * Names of files imported by this file.
     * </pre>
     *
     * <code>repeated string dependency = 3;</code>
     * @param value The dependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.add(value: kotlin.String) {
      _builder.addDependency(value)
    }
    /**
     * <pre>
     * Names of files imported by this file.
     * </pre>
     *
     * <code>repeated string dependency = 3;</code>
     * @param value The dependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <pre>
     * Names of files imported by this file.
     * </pre>
     *
     * <code>repeated string dependency = 3;</code>
     * @param values The dependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllDependency(values)
    }
    /**
     * <pre>
     * Names of files imported by this file.
     * </pre>
     *
     * <code>repeated string dependency = 3;</code>
     * @param values The dependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <pre>
     * Names of files imported by this file.
     * </pre>
     *
     * <code>repeated string dependency = 3;</code>
     * @param index The index to set the value at.
     * @param value The dependency to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setDependency")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setDependency(index, value)
    }/**
     * <pre>
     * Names of files imported by this file.
     * </pre>
     *
     * <code>repeated string dependency = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, DependencyProxy>.clear() {
      _builder.clearDependency()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PublicDependencyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Indexes of the public imported files in the dependency list above.
     * </pre>
     *
     * <code>repeated int32 public_dependency = 10;</code>
     */
     public val publicDependency: com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPublicDependencyList()
      )
    /**
     * <pre>
     * Indexes of the public imported files in the dependency list above.
     * </pre>
     *
     * <code>repeated int32 public_dependency = 10;</code>
     * @param value The publicDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPublicDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.add(value: kotlin.Int) {
      _builder.addPublicDependency(value)
    }/**
     * <pre>
     * Indexes of the public imported files in the dependency list above.
     * </pre>
     *
     * <code>repeated int32 public_dependency = 10;</code>
     * @param value The publicDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPublicDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * <pre>
     * Indexes of the public imported files in the dependency list above.
     * </pre>
     *
     * <code>repeated int32 public_dependency = 10;</code>
     * @param values The publicDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPublicDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllPublicDependency(values)
    }/**
     * <pre>
     * Indexes of the public imported files in the dependency list above.
     * </pre>
     *
     * <code>repeated int32 public_dependency = 10;</code>
     * @param values The publicDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPublicDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * <pre>
     * Indexes of the public imported files in the dependency list above.
     * </pre>
     *
     * <code>repeated int32 public_dependency = 10;</code>
     * @param index The index to set the value at.
     * @param value The publicDependency to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPublicDependency")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setPublicDependency(index, value)
    }/**
     * <pre>
     * Indexes of the public imported files in the dependency list above.
     * </pre>
     *
     * <code>repeated int32 public_dependency = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPublicDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, PublicDependencyProxy>.clear() {
      _builder.clearPublicDependency()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WeakDependencyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     * </pre>
     *
     * <code>repeated int32 weak_dependency = 11;</code>
     */
     public val weakDependency: com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getWeakDependencyList()
      )
    /**
     * <pre>
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     * </pre>
     *
     * <code>repeated int32 weak_dependency = 11;</code>
     * @param value The weakDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addWeakDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.add(value: kotlin.Int) {
      _builder.addWeakDependency(value)
    }/**
     * <pre>
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     * </pre>
     *
     * <code>repeated int32 weak_dependency = 11;</code>
     * @param value The weakDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignWeakDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * <pre>
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     * </pre>
     *
     * <code>repeated int32 weak_dependency = 11;</code>
     * @param values The weakDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllWeakDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllWeakDependency(values)
    }/**
     * <pre>
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     * </pre>
     *
     * <code>repeated int32 weak_dependency = 11;</code>
     * @param values The weakDependency to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllWeakDependency")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * <pre>
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     * </pre>
     *
     * <code>repeated int32 weak_dependency = 11;</code>
     * @param index The index to set the value at.
     * @param value The weakDependency to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setWeakDependency")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setWeakDependency(index, value)
    }/**
     * <pre>
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     * </pre>
     *
     * <code>repeated int32 weak_dependency = 11;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearWeakDependency")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeakDependencyProxy>.clear() {
      _builder.clearWeakDependency()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MessageTypeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * All top-level definitions in this file.
     * </pre>
     *
     * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
     */
     public val messageType: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMessageTypeList()
      )
    /**
     * <pre>
     * All top-level definitions in this file.
     * </pre>
     *
     * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
     * @param value The messageType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMessageType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.add(value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      _builder.addMessageType(value)
    }/**
     * <pre>
     * All top-level definitions in this file.
     * </pre>
     *
     * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
     * @param value The messageType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMessageType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      add(value)
    }/**
     * <pre>
     * All top-level definitions in this file.
     * </pre>
     *
     * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
     * @param values The messageType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMessageType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto>) {
      _builder.addAllMessageType(values)
    }/**
     * <pre>
     * All top-level definitions in this file.
     * </pre>
     *
     * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
     * @param values The messageType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMessageType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.DescriptorProto>) {
      addAll(values)
    }/**
     * <pre>
     * All top-level definitions in this file.
     * </pre>
     *
     * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
     * @param index The index to set the value at.
     * @param value The messageType to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMessageType")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.DescriptorProto) {
      _builder.setMessageType(index, value)
    }/**
     * <pre>
     * All top-level definitions in this file.
     * </pre>
     *
     * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMessageType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.DescriptorProto, MessageTypeProxy>.clear() {
      _builder.clearMessageType()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class EnumTypeProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
     */
     public val enumType: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getEnumTypeList()
      )
    /**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
     * @param value The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.add(value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      _builder.addEnumType(value)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
     * @param value The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignEnumType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
     * @param values The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumDescriptorProto>) {
      _builder.addAllEnumType(values)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
     * @param values The enumType to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllEnumType")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.EnumDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
     * @param index The index to set the value at.
     * @param value The enumType to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setEnumType")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.EnumDescriptorProto) {
      _builder.setEnumType(index, value)
    }/**
     * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearEnumType")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.EnumDescriptorProto, EnumTypeProxy>.clear() {
      _builder.clearEnumType()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ServiceProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
     */
     public val service: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getServiceList()
      )
    /**
     * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
     * @param value The service to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addService")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.add(value: com.google.protobuf.DescriptorProtos.ServiceDescriptorProto) {
      _builder.addService(value)
    }/**
     * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
     * @param value The service to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignService")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.ServiceDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
     * @param values The service to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllService")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto>) {
      _builder.addAllService(values)
    }/**
     * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
     * @param values The service to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllService")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
     * @param index The index to set the value at.
     * @param value The service to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setService")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.ServiceDescriptorProto) {
      _builder.setService(index, value)
    }/**
     * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearService")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.ServiceDescriptorProto, ServiceProxy>.clear() {
      _builder.clearService()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ExtensionProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
     */
     public val extension: com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getExtensionList()
      )
    /**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
     * @param value The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.add(value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      _builder.addExtension(value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
     * @param value The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignExtension")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.plusAssign(value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      add(value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
     * @param values The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.addAll(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FieldDescriptorProto>) {
      _builder.addAllExtension(values)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
     * @param values The extension to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllExtension")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.plusAssign(values: kotlin.collections.Iterable<com.google.protobuf.DescriptorProtos.FieldDescriptorProto>) {
      addAll(values)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
     * @param index The index to set the value at.
     * @param value The extension to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setExtension")
    public operator fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.set(index: kotlin.Int, value: com.google.protobuf.DescriptorProtos.FieldDescriptorProto) {
      _builder.setExtension(index, value)
    }/**
     * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearExtension")
    public fun com.google.protobuf.kotlin.DslList<com.google.protobuf.DescriptorProtos.FieldDescriptorProto, ExtensionProxy>.clear() {
      _builder.clearExtension()
    }
    /**
     * <code>optional .google.protobuf.FileOptions options = 8;</code>
     */
    public var options: com.google.protobuf.DescriptorProtos.FileOptions
      @JvmName("getOptions")
      get() = _builder.getOptions()
      @JvmName("setOptions")
      set(value) {
        _builder.setOptions(value)
      }
    /**
     * <code>optional .google.protobuf.FileOptions options = 8;</code>
     */
    public fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * <code>optional .google.protobuf.FileOptions options = 8;</code>
     * @return Whether the options field is set.
     */
    public fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }

    /**
     * <pre>
     * This field contains optional information about the original source code.
     * You may safely remove this entire field without harming runtime
     * functionality of the descriptors -- the information is needed only by
     * development tools.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9;</code>
     */
    public var sourceCodeInfo: com.google.protobuf.DescriptorProtos.SourceCodeInfo
      @JvmName("getSourceCodeInfo")
      get() = _builder.getSourceCodeInfo()
      @JvmName("setSourceCodeInfo")
      set(value) {
        _builder.setSourceCodeInfo(value)
      }
    /**
     * <pre>
     * This field contains optional information about the original source code.
     * You may safely remove this entire field without harming runtime
     * functionality of the descriptors -- the information is needed only by
     * development tools.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9;</code>
     */
    public fun clearSourceCodeInfo() {
      _builder.clearSourceCodeInfo()
    }
    /**
     * <pre>
     * This field contains optional information about the original source code.
     * You may safely remove this entire field without harming runtime
     * functionality of the descriptors -- the information is needed only by
     * development tools.
     * </pre>
     *
     * <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9;</code>
     * @return Whether the sourceCodeInfo field is set.
     */
    public fun hasSourceCodeInfo(): kotlin.Boolean {
      return _builder.hasSourceCodeInfo()
    }

    /**
     * <pre>
     * The syntax of the proto file.
     * The supported values are "proto2" and "proto3".
     * </pre>
     *
     * <code>optional string syntax = 12;</code>
     */
    public var syntax: kotlin.String
      @JvmName("getSyntax")
      get() = _builder.getSyntax()
      @JvmName("setSyntax")
      set(value) {
        _builder.setSyntax(value)
      }
    /**
     * <pre>
     * The syntax of the proto file.
     * The supported values are "proto2" and "proto3".
     * </pre>
     *
     * <code>optional string syntax = 12;</code>
     */
    public fun clearSyntax() {
      _builder.clearSyntax()
    }
    /**
     * <pre>
     * The syntax of the proto file.
     * The supported values are "proto2" and "proto3".
     * </pre>
     *
     * <code>optional string syntax = 12;</code>
     * @return Whether the syntax field is set.
     */
    public fun hasSyntax(): kotlin.Boolean {
      return _builder.hasSyntax()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.google.protobuf.DescriptorProtos.FileDescriptorProto.copy(block: com.google.protobuf.FileDescriptorProtoKt.Dsl.() -> kotlin.Unit): com.google.protobuf.DescriptorProtos.FileDescriptorProto =
  com.google.protobuf.FileDescriptorProtoKt.Dsl._create(this.toBuilder()).apply { block() }._build()
